import {
  LayoutDashboard, Users, Building, Wrench, UserPlus,
  CalendarCheck, Star, Receipt, Megaphone, Home,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface OrbitalNode {
  id: number;
  title: string;
  date: string;
  content: string;
  category: string;
  icon: LucideIcon;
  relatedIds: number[];
  status: "completed" | "in-progress" | "pending";
  energy: number;
  route: string;
}

export const adminNodes: OrbitalNode[] = [
  {
    id: 1,
    title: "数据仪表盘",
    date: "监控面板",
    content: "宿舍管理系统数据概览与统计分析",
    category: "监控面板",
    icon: LayoutDashboard,
    relatedIds: [2, 3],
    status: "in-progress",
    energy: 90,
    route: "/dashboard",
  },
  {
    id: 2,
    title: "学生管理",
    date: "基础管理",
    content: "管理学生信息、学号及宿舍分配",
    category: "基础管理",
    icon: Users,
    relatedIds: [1, 3],
    status: "completed",
    energy: 85,
    route: "/admin/students",
  },
  {
    id: 3,
    title: "宿舍管理",
    date: "基础管理",
    content: "管理宿舍楼栋与房间信息",
    category: "基础管理",
    icon: Building,
    relatedIds: [1, 2],
    status: "completed",
    energy: 80,
    route: "/admin/dormitories",
  },
  {
    id: 4,
    title: "报修管理",
    date: "业务管理",
    content: "处理宿舍报修申请与维修工单",
    category: "业务管理",
    icon: Wrench,
    relatedIds: [5, 6],
    status: "in-progress",
    energy: 75,
    route: "/admin/repairs",
  },
  {
    id: 5,
    title: "访客管理",
    date: "业务管理",
    content: "审批访客预约与访问记录查询",
    category: "业务管理",
    icon: UserPlus,
    relatedIds: [4, 6],
    status: "pending",
    energy: 60,
    route: "/admin/visitors",
  },
  {
    id: 6,
    title: "请假审批",
    date: "业务管理",
    content: "审批学生请假申请与销假管理",
    category: "业务管理",
    icon: CalendarCheck,
    relatedIds: [4, 5],
    status: "pending",
    energy: 55,
    route: "/admin/leaves",
  },
  {
    id: 7,
    title: "评分录入",
    date: "业务管理",
    content: "宿舍卫生与纪律评分管理",
    category: "业务管理",
    icon: Star,
    relatedIds: [8],
    status: "completed",
    energy: 70,
    route: "/admin/scores",
  },
  {
    id: 8,
    title: "水电管理",
    date: "业务管理",
    content: "宿舍水电费用账单管理",
    category: "业务管理",
    icon: Receipt,
    relatedIds: [7, 9],
    status: "pending",
    energy: 50,
    route: "/admin/utility",
  },
  {
    id: 9,
    title: "公告管理",
    date: "业务管理",
    content: "发布与管理宿舍公告通知",
    category: "业务管理",
    icon: Megaphone,
    relatedIds: [8],
    status: "completed",
    energy: 90,
    route: "/admin/announcements",
  },
];

export const studentNodes: OrbitalNode[] = [
  {
    id: 1,
    title: "宿舍环境监控",
    date: "我的宿舍",
    content: "实时查看宿舍温度、湿度、烟雾数据",
    category: "我的宿舍",
    icon: Home,
    relatedIds: [2, 3],
    status: "in-progress",
    energy: 95,
    route: "/monitor",
  },
  {
    id: 2,
    title: "报修申请",
    date: "生活服务",
    content: "提交宿舍报修工单，查看处理进度",
    category: "生活服务",
    icon: Wrench,
    relatedIds: [1, 3],
    status: "in-progress",
    energy: 80,
    route: "/student/repairs",
  },
  {
    id: 3,
    title: "访客预约",
    date: "生活服务",
    content: "为访客预约进入宿舍楼",
    category: "生活服务",
    icon: UserPlus,
    relatedIds: [1, 2],
    status: "pending",
    energy: 60,
    route: "/student/visitors",
  },
  {
    id: 4,
    title: "请假申请",
    date: "生活服务",
    content: "提交请假申请，查看审批状态",
    category: "生活服务",
    icon: CalendarCheck,
    relatedIds: [5],
    status: "pending",
    energy: 55,
    route: "/student/leave",
  },
  {
    id: 5,
    title: "宿舍评分",
    date: "生活服务",
    content: "查看宿舍卫生与纪律评分",
    category: "生活服务",
    icon: Star,
    relatedIds: [4, 6],
    status: "completed",
    energy: 75,
    route: "/student/scores",
  },
  {
    id: 6,
    title: "水电账单",
    date: "生活服务",
    content: "查看宿舍水电费用与账单明细",
    category: "生活服务",
    icon: Receipt,
    relatedIds: [5],
    status: "pending",
    energy: 50,
    route: "/student/utility",
  },
  {
    id: 7,
    title: "公告通知",
    date: "生活服务",
    content: "查看宿舍最新公告与通知消息",
    category: "生活服务",
    icon: Megaphone,
    relatedIds: [],
    status: "completed",
    energy: 85,
    route: "/student/announcements",
  },
];

export function getNodesForRole(isAdmin: boolean): OrbitalNode[] {
  return isAdmin ? adminNodes : studentNodes;
}
